name: Build Howl

on:
  push:
    branches: [ gh-actions ]


jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Restore Gradle cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-grad

      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Howl
          path: /build/outputs/apk/
